from src.diffeomorphisms.composition.image import ImageCompositionDiffeomorphism
from src.diffeomorphisms.image.to_vec import ToVecImageDiffeomorphism
from src.diffeomorphisms.vector.poincare import PoincareVectorDiffeomorphism

from src.manifolds.euclidean.image.pullback import PullbackImageEuclidean
from src.manifolds.hyperbolic.vector.standard import StandardVectorHyperbolic

class HyperbolicPullbackImageEuclidean(PullbackImageEuclidean):
    """ Base class describing a R^d under a hyperbolic-pullback Riemannian geometry generated by a Diffeomorphism that maps into R^d and is then embedded into the Poincaré ball """

    def __init__(self, diffeomorphism, needs_embedding=True):
        if needs_embedding:
            image_to_vec_diffeo = ToVecImageDiffeomorphism(diffeomorphism.C, diffeomorphism.H, diffeomorphism.W)
            poincare_diffeo = PoincareVectorDiffeomorphism(diffeomorphism.d)
            full_diffeo = ImageCompositionDiffeomorphism([diffeomorphism, image_to_vec_diffeo, poincare_diffeo], diffeomorphism.C, diffeomorphism.H, diffeomorphism.W)
        else:
            full_diffeo = diffeomorphism
        super().__init__(StandardVectorHyperbolic(diffeomorphism.d), full_diffeo)
