from src.diffeomorphisms.composition.image import ImageCompositionDiffeomorphism
from src.diffeomorphisms.image.to_vec import ToVecImageDiffeomorphism

from src.manifolds.euclidean.image.pullback import PullbackImageEuclidean
from src.manifolds.product import ProductVectorEuclidean

class ProductPullbackImageEuclidean(PullbackImageEuclidean):
    """ Base class describing a R^d under a product-pullback Riemannian geometry generated by a Diffeomorphism that maps into R^d and is then embedded into a product manifold """

    def __init__(self, manifolds, diffeomorphism, product_embedding, structured_linear=None):
        image_to_vec_diffeo = ToVecImageDiffeomorphism(diffeomorphism.C, diffeomorphism.H, diffeomorphism.W)
        if structured_linear is not None:
            full_diffeo = ImageCompositionDiffeomorphism([diffeomorphism, image_to_vec_diffeo, structured_linear, product_embedding], diffeomorphism.C, diffeomorphism.H, diffeomorphism.W)
        else:
            full_diffeo = ImageCompositionDiffeomorphism([diffeomorphism, image_to_vec_diffeo, product_embedding], diffeomorphism.C, diffeomorphism.H, diffeomorphism.W)

        super().__init__(ProductVectorEuclidean(manifolds), full_diffeo)