from src.diffeomorphisms.composition import CompositionDiffeomorphism
from src.diffeomorphisms.vector.poincare import PoincareVectorDiffeomorphism

from src.manifolds.euclidean.vector.pullback import PullbackVectorEuclidean
from src.manifolds.hyperbolic.vector.standard import StandardVectorHyperbolic

class HyperbolicdPullbackVectorEuclidean(PullbackVectorEuclidean):
    """ Base class describing a R^d under a hyperbolic-pullback Riemannian geometry generated by a Diffeomorphism that maps into R^d and is then embedded into the Poincaré ball """

    def __init__(self, diffeomorphism, needs_embedding=True):
        if needs_embedding:
            poincare_diffeo = PoincareVectorDiffeomorphism(diffeomorphism.d)
            full_diffeo = CompositionDiffeomorphism([diffeomorphism, poincare_diffeo])
        else:
            full_diffeo = diffeomorphism
        super().__init__(StandardVectorHyperbolic(diffeomorphism.d), full_diffeo)
