experiments:
  mnist_32:
    data:
      size: 32
      batch_size: 128
      mnist_mean: 0.1307
      mnist_var: 0.3081
      train_val_split: 0.8

    emb:
      enabled: true
      num_epochs: 50          
      learning_rate: 1.0e-2  
      reg_param: 1.0e-2   
      latent_dim: 16 
      checkpoint_subdir: "checkpoints_emb"

    phi:
      enabled: false
      num_epochs: 100         
      learning_rate: 1.0e-3  
      reg_param: 1.0e-4 
      sigma: 1.0e-2               
      in_channels: 1
      squeeze_factor: 2
      kernel_size: 3
      hidden_channels: 32
      n_flows: 6
      n_scales: 3
      checkpoint_subdir: "checkpoints_phi"

    starflow:
      enabled: true
      reg_param: 1.0e-12
      n_clusters: 10
      trimmed: true
