from src.diffeomorphisms.composition import CompositionDiffeomorphism

from src.manifolds.euclidean.vector.pullback import PullbackVectorEuclidean
from src.manifolds.product import ProductVectorEuclidean

class ProductPullbackVectorEuclidean(PullbackVectorEuclidean):
    """ Base class describing a R^d under a product-pullback Riemannian geometry generated by a Diffeomorphism that maps into R^d and is then embedded into a product manifold """

    def __init__(self, manifolds, diffeomorphism, product_embedding, structured_linear=None):
        if structured_linear is not None:
            full_diffeo = CompositionDiffeomorphism([diffeomorphism, structured_linear, product_embedding])
        else:
            full_diffeo = CompositionDiffeomorphism([diffeomorphism, product_embedding])
        super().__init__(ProductVectorEuclidean(manifolds), full_diffeo)

    # TODO overwrite manifold mappings

    def barycentre(self, x, tol=None, max_iter=None, step_size=None, red_coef=None): # TODO: debug
        """

        :param x: N x d
        :return: d
        """
        return self.phi.inverse([p[None] for p in self.manifold.barycentre(self.phi.forward(x), tol=tol, max_iter=max_iter, step_size=step_size, red_coef=red_coef)])[0]

    def inner(self, x, X, Y):
        """

        :param x: N x d
        :param X: N x M x d
        :param Y: N x L x d
        :return: N x M x L
        """
        M = X.shape[1]
        L = Y.shape[1]
        return self.manifold.inner(self.phi.forward(x),
                                   [P.reshape(X.shape[:-1], -1) for P in self.phi.differential_forward((x[:, None].repeat(1,M,1)).reshape(-1, self.d), X.reshape(-1, self.d))],
                                   [P.reshape(Y.shape[:-1], -1) for P in self.phi.differential_forward((x[:, None].repeat(1,L,1)).reshape(-1, self.d), Y.reshape(-1, self.d))]
                                   )
    
    def norm(self, x, X): # TODO: debug
        """

        :param x: N x d
        :param X: N x M x d
        :return: N x M
        """
        N, M = X.shape[:2]
        
        phi_x = [p[:,None].repeat(1,M,1).reshape(N * M, -1) for p in self.phi.forward(x)]
        phi_X = [P.reshape(N,M,-1) for P in self.phi.differential_forward((x[:, None].repeat(1,M,1)).reshape(-1, self.d), X.reshape(-1, self.d))]
        return self.manifold.inner(phi_x, phi_X, phi_X).sqrt().reshape(-1, M)

    def geodesic(self, x, y, t):
        """

        :param x: N x M x d
        :param y: N x L x d
        :param t: K or N x M x L x K
        :return: N x M x L x K x d
        """
        N, M, d = x.shape
        L = y.shape[1]
        K = t.shape[-1]

        # Flatten and map through phi
        phi_x = [p.reshape(N, M, -1) for p in self.phi.forward(x.reshape(-1, d))]
        phi_y = [p.reshape(N, L, -1) for p in self.phi.forward(y.reshape(-1, d))]

        # Weighted combination in phi-space
        phi_geo = [p.reshape(N * M * L * K, -1) for p in self.manifold.geodesic(phi_x, phi_y, t)]

        # Flatten batch for single call to phi inverse
        return self.phi.inverse(phi_geo).reshape(N, M, L, K, d)
            
    def log(self, x, y): # TODO: debug
        """

        :param x: N x M x d
        :param y: N x L x d
        :return: N x M x L x d
        """
        N, M, d = x.shape
        L = y.shape[1]

        # Flatten and map through phi
        phi_x = [p.reshape(N, M, -1) for p in self.phi.forward(x.reshape(-1, d))]
        phi_y = [p.reshape(N, L, -1) for p in self.phi.forward(y.reshape(-1, d))]

        # log in phi-space
        phi_log = [P.reshape(N * M * L, -1) for P in self.manifold.log(phi_x, phi_y)]

        # Flatten batch for single call to differential phi inverse
        return self.phi.differential_inverse([p[:,:,None].repeat(1,1,L,1).reshape(N * M * L, -1) for p in phi_x], phi_log).reshape(N, M, L, d)

    def exp(self, x, X): # TODO: debug
        """

        :param x: N x d
        :param X: N x M x d
        :return: N x M x d
        """
        N, d = x.shape
        M = X.shape[1]

        # Flatten and map through phi
        phi_x = [p.reshape(N, -1) for p in self.phi.forward(x.reshape(-1, d))]
        phi_X = [P.reshape(N, M, -1) for P in self.phi.differential_forward((x[:, None].repeat(1, M, 1)).reshape(-1, d), X.reshape(-1, d))]

        # exp in phi-space
        phi_exp = self.manifold.exp(phi_x, phi_X)

        # Flatten batch for single call to phi inverse
        return self.phi.inverse([p.reshape(N * M, -1) for p in phi_exp]).reshape(N, M, d)

    def distance(self, x, y): # TODO: debug
        """

        :param x: N x M x d
        :param y: N x L x d
        :return: N x M x L
        """
        N, M, d = x.shape
        L = y.shape[1]

        # Flatten and map through phi
        phi_x = [p.reshape(N, M, -1) for p in self.phi.forward(x.reshape(-1, d))]
        phi_y = [p.reshape(N, L, -1) for p in self.phi.forward(y.reshape(-1, d))]

        # distance in phi-space
        return self.manifold.distance(phi_x, phi_y).reshape(N, M, L)

    def parallel_transport(self, x, X, y): # TODO: debug
        """

        :param x: N x M x d
        :param X: N x M x K x d
        :param y: N x L x d
        :return: N x M x L x K x d
        """
        N, M, d = x.shape
        L = y.shape[1]
        K = X.shape[2]

        # Flatten and map through phi
        phi_x = [p.reshape(N, M, -1) for p in self.phi.forward(x.reshape(-1, d))]
        phi_y = [p.reshape(N, L, -1) for p in self.phi.forward(y.reshape(-1, d))]
        phi_X = [P.reshape(N, M, K, -1) for P in self.phi.differential_forward((x[:, :, None].repeat(1, 1, K, 1)).reshape(-1, d), X.reshape(-1, d))]

        # parallel transport in phi-space
        phi_pt = [P.reshape(N, M, L, K, -1) for P in self.manifold.parallel_transport(phi_x, phi_X, phi_y)]

        # Flatten batch for single call to differential phi inverse
        return self.phi.differential_inverse((phi_y[:, None].repeat(1, M, 1, K, 1)).reshape(-1, d), phi_pt.reshape(-1, d)).reshape(N, M, L, K, d)