from src.diffeomorphisms.vector.product_embedding.poincare_identity import PoincareIdentityVectorDiffeomorphism
from src.manifolds.euclidean.vector.pullback.product import ProductPullbackVectorEuclidean
from src.manifolds.euclidean.vector.standard import StandardVectorEuclidean
from src.manifolds.hyperbolic.vector.standard import StandardVectorHyperbolic

class HyperbolicEuclideanPullbackVectorEuclidean(ProductPullbackVectorEuclidean):
    """ Base class describing a R^d under a product-pullback Riemannian geometry generated by a Diffeomorphism that maps into R^d and is then embedded into a product manifold of a hyperbolic and a Euclidean space """

    def __init__(self, diffeomorphism, r=None, structured_linear=None):
        if r is None:
            assert structured_linear is not None, "Either the Poincaré ball dimension r or a structured linear Diffeomorphism must be provided"
            r = structured_linear.r
        super().__init__([StandardVectorHyperbolic(r), StandardVectorEuclidean(diffeomorphism.d - r)], diffeomorphism, PoincareIdentityVectorDiffeomorphism(diffeomorphism.d, r), structured_linear)