import torch
from src.manifolds.euclidean.image import ImageEuclidean

class PullbackImageEuclidean(ImageEuclidean):
    """ Base class describing a R^d under a pullback Riemannian geometry generated by a Diffeomorphism """

    def __init__(self, image_manifold, image_diffeomorphism):
        super().__init__(image_diffeomorphism.C, image_diffeomorphism.H, image_diffeomorphism.W)
        self.phi = image_diffeomorphism 
        self.manifold = image_manifold

    def barycentre(self, x, weights=None, tol=None, max_iter=None, step_size=None, red_coef=None):
        """

        :param x: N x (C x H x W) 
        :param weights: N x M
        :return: M x (C x H x W) 
        """
        N = x.shape[0]
        if weights is not None:
            M = weights.shape[1]
        else:
            M = 1
        return self.phi.inverse(self.manifold.barycentre(self.phi.forward(x).reshape(N, self.d), weights=weights, tol=tol, max_iter=max_iter, step_size=step_size, red_coef=red_coef).reshape(-1, self.C, self.H, self.W)).reshape(M, self.C, self.H, self.W)

    def inner(self, x, X, Y):
        """

        :param x: N x (C x H x W) 
        :param X: N x M x (C x H x W) 
        :param Y: N x L x (C x H x W) 
        :return: N x M x L
        """
        N = x.shape[0]
        M = X.shape[1]
        L = Y.shape[1]
        return self.manifold.inner(self.phi.forward(x).reshape(N, self.d),
                                   self.phi.differential_forward((x[:, None].repeat(1,M,1,1,1)).reshape(-1, self.C, self.H, self.W), X.reshape(-1, self.C, self.H, self.W)).reshape(N, M, self.d),
                                   self.phi.differential_forward((x[:, None].repeat(1,L,1,1,1)).reshape(-1, self.C, self.H, self.W), Y.reshape(-1, self.C, self.H, self.W)).reshape(N, L, self.d)
                                   )

    def geodesic(self, x, y, t): 
        """

        :param x: N x M x (C x H x W) 
        :param y: N x L x (C x H x W) 
        :param t: K or N x M x L x K
        :return: N x M x L x K x (C x H x W)
        """
        N, M, C, H, W = x.shape
        L = y.shape[1]
        K = t.shape[-1]

        # Flatten and map through phi
        phi_x = self.phi.forward(x.reshape(-1, C, H, W)).reshape(N, M, self.d) 
        phi_y = self.phi.forward(y.reshape(-1, C, H, W)).reshape(N, L, self.d) 

        # Weighted combination in phi-space
        phi_geo = self.manifold.geodesic(phi_x, phi_y, t)

        # Flatten batch for single call to phi inverse
        return self.phi.inverse(phi_geo.reshape(-1, C, H, W)).reshape(N, M, L, K, C, H, W)    

    def log(self, x, y): 
        """

        :param x: N x M x (C x H x W)
        :param y: N x L x (C x H x W)
        :return: N x M x L x (C x H x W)
        """
        N, M, C, H, W = x.shape
        L = y.shape[1]

        # Flatten and map through phi
        phi_x = self.phi.forward(x.reshape(-1, C, H, W)).reshape(N, M, self.d) 
        phi_y = self.phi.forward(y.reshape(-1, C, H, W)).reshape(N, L, self.d) 

        # log in phi-space
        phi_log = self.manifold.log(phi_x, phi_y)

        # Flatten batch for single call to differential phi inverse
        return self.phi.differential_inverse(phi_x[:,:,None].repeat(1,1,L,1).reshape(-1, C, H, W),phi_log.reshape(-1, C, H, W)).reshape(N, M, L, C, H, W)

    def exp(self, x, X): 
        """

        :param x: N x (C x H x W)
        :param X: N x M x (C x H x W)
        :return: N x M x (C x H x W)
        """
        N, C, H, W = x.shape
        M = X.shape[1]

        # Flatten and map through phi
        phi_x = self.phi.forward(x.reshape(-1, C, H, W)).reshape(N, self.d)
        phi_X = self.phi.differential_forward((x[:, None].repeat(1, M, 1, 1, 1)).reshape(-1, C, H, W), X.reshape(-1, C, H, W)).reshape(N, M, self.d)

        # exp in phi-space
        phi_exp = self.manifold.exp(phi_x, phi_X)

        # Flatten batch for single call to phi inverse
        return self.phi.inverse(phi_exp.reshape(-1, self.C, self.H, self.W)).reshape(N, M, C, H, W)
    
    def distance(self, x, y):
        """

        :param x: N x M x (C x H x W)
        :param y: N x L x (C x H x W)
        :return: N x M x L
        """
        N, M, C, H, W = x.shape
        L = y.shape[1]

        # Flatten and map through phi
        phi_x = self.phi.forward(x.reshape(-1, C, H, W)).reshape(N, M, self.d) 
        phi_y = self.phi.forward(y.reshape(-1, C, H, W)).reshape(N, L, self.d) 

        # distance in phi-space
        return self.manifold.distance(phi_x, phi_y).reshape(N, M, L)

    def parallel_transport(self, x, X, y): 
        """

        :param x: N x M x (C x H x W)
        :param X: N x M x K x (C x H x W)
        :param y: N x L x (C x H x W)
        :return: N x M x L x K x (C x H x W)
        """
        N, M, C, H, W = x.shape
        L = y.shape[1]
        K = X.shape[2]

        # Flatten and map through phi
        phi_x = self.phi.forward(x.reshape(-1, C, H, W)).reshape(N, M, self.d)
        phi_y = self.phi.forward(y.reshape(-1, C, H, W)).reshape(N, L, self.d)
        phi_X = self.phi.differential_forward((x[:, :, None].repeat(1, 1, K, 1, 1, 1)).reshape(-1, C, H, W), X.reshape(-1, C, H, W)).reshape(N, M, K, self.d)

        # parallel transport in phi-space
        phi_pt = self.manifold.parallel_transport(phi_x, phi_X, phi_y).reshape(N, M, L, K, self.d)

        # Flatten batch for single call to differential phi inverse
        return self.phi.differential_inverse((phi_y[:, None].repeat(1, M, 1, K, 1)).reshape(-1, self.d), phi_pt.reshape(-1, self.d)).reshape(N, M, L, K, C, H, W)
    