from src.manifolds.euclidean.image.pullback import PullbackImageEuclidean
from src.manifolds.euclidean.vector.standard import StandardVectorEuclidean

class StandardPullbackImageEuclidean(PullbackImageEuclidean):
    """ Base class describing a R^d under a l^2-pullback Riemannian geometry generated by a Diffeomorphism """

    def __init__(self, image_diffeomorphism):
        super().__init__(StandardVectorEuclidean(image_diffeomorphism.d), image_diffeomorphism)